
POST http://localhost:8090/api/tx HTTP/1.1
content-type: application/json

{
  "type": "newOrderTx",
  "sessionId": "test-session",
  "clOrdId": "20250904-test-001",
  "sendingTime": "2025-09-04T10:44:00",
  "account": "account-01",
  "execInst": "NO_CROSS",
  "handlInst": "BROKER_INTERVENTION_OK",
  "securityIdSource": "RIC",
  "orderQty": 100,
  "priceType": "PER_UNIT",
  "ordType": "LIMIT",
  "price": 22.35,
  "securityId": "INTC.OQ",
  "securityDesc": "Intel Corporation",
  "side": "BUY",
  "symbol": "INTC",
  "timeInForce": "DAY",
  "transactTime": "2025-09-04T10:01:00",
  "exDestination": "XNAS",
  "settlCurrency": "USD",
  "securityExchange": "XNAS",
  "text": "Sample order"
}

###
GET http://localhost:8090/api/query/orders?symbol=INTC&side=BUY HTTP/1.1
content-type: application/json

###
GET http://localhost:8090/api/query/orders?price__between=20,40 HTTP/1.1
content-type: application/json

###
GET http://localhost:8090/api/query/orders?sendingTime__between=2025-08-01T00:00:00,2025-08-28T23:59:59 HTTP/1.1
content-type: application/json