
POST http://localhost:8090/api/tx HTTP/1.1
content-type: application/json

{
  "type": "newOrderTx",
  "sessionId": "test-session",
  "clOrdId": "20250504-test-001",
  "sendingTime": "2024-05-04T10:00:00",
  "account": "account-01",
  "execInst": "NO_CROSS",
  "handlInst": "BROKER_INTERVENTION_OK",
  "securityIDSource": "RIC",
  "orderQty": 100,
  "priceType": "PER_UNIT",
  "ordType": "LIMIT",
  "price": 23.50,
  "securityId": "INTC.OQ",
  "side": "BUY",
  "symbol": "INTC",
  "timeInForce": "DAY",
  "transactTime": "2024-03-09T10:01:00",
  "exDestination": "XNAS",
  "settlCurrency": "USD",
  "securityExchange": "XNAS",
  "text": "Sample order"
}