apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: oms
build:
  artifacts:
    - image: oms
      docker:
        dockerfile: Dockerfile
  local:
    push: true
deploy:
  kubectl:
    manifests:
      - k8s/oms-deployment.yaml
      - k8s/oms-service.yaml
  kustomize:
    paths:
      - k8s
    images:
      - name: oms
        newName: oms
        newTag: latest
  helm:
    releases:
      - name: oms
        chartPath: charts/oms
        valuesFiles:
          - charts/oms/values.yaml
        setValues:
          image.repository: oms
          image.tag: latest
manifests:
  rawYaml:
    - k8s/oms-deployment.yaml
    - k8s/oms-service.yaml