apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: oms
  name: oms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: oms
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: oms
    spec:
      containers:
        - env:
            - name: CONSUMER_GROUP
              value: oms_consumer_group
            - name: DB_PASSWORD
              value: changeme
            - name: DB_URL
              value: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true
            - name: DB_USER
              value: postgres
            - name: DEAD_LETTER_TOPIC
              value: oms_dlq
            - name: KAFKA_BROKERS
              value: localhost:9092
            - name: ORDER_TOPIC
              value: oms_orders
            - name: REGISTRY_URL
              value: http://localhost:8081
            - name: SERVER_PORT
              value: "8090"
            - name: TRACING_URL
              value: http://localhost:4317
            - name: TX_ID_PREFIX
              value: tx-
          image: oms:latest
          name: oms
          ports:
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
